import { FC, useState } from 'react';
import Head from 'next/head';
import { useAppDispatch, useAppSelector } from 'hooks';
import { decrement, increment, incrementByAmount, selectCount } from 'store/counter';
import { Container } from './index.styles';

export const Home: FC = () => {
    const dispatch = useAppDispatch();
    const count = useAppSelector(selectCount);
    const [incAmount, setIncAmount] = useState<number>(0);

    return (
        <div>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container>
                <h1>{count}</h1>
                <div>
                    <input
                        value={incAmount}
                        onChange={(e) => setIncAmount(Number(e.target.value))}
                        type="number"
                    />
                    <button onClick={() => dispatch(incrementByAmount(Number(incAmount)))}>
                        Increment by amount
                    </button>
                </div>
                <div>
                    <button onClick={() => dispatch(decrement())}>Decrement by 1</button>
                    <button onClick={() => dispatch(increment())}>Increment by 1</button>
                </div>
            </Container>
        </div>
    );
};

export default Home;
